CREATE DATABASE douhu
CREATE TABLE IF NOT EXISTS article (
  id INT(12) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  article_type INT(12) NOT NULL,
  title TEXT NOT NULL,
  intro TEXT NOT NULL,
  imgUrl TEXT NOT NULL,
  link TEXT NOT NULL
) DEFAULT CHARACTER SET gbk COLLATE gbk_chinese_ci